apiVersion: v1
kind: Secret
metadata:
  name: xstream-backend-env
type: Opaque
stringData:
  PORT: "8000"
  BASE_URL: "http://APP_PUBLIC_IP:30080"
  DATABASE: "mongodb+srv://replace-me"
  API_ID: "replace-me"
  API_HASH: "replace-me"
  BOT_TOKEN: "replace-me"
  AUTH_CHANNEL: "replace-me"
  TMDB_API: "replace-me"
  IMDB_API: "replace-me"
  OWNER_ID: "replace-me"
  USE_CAPTION: "True"
  USE_TMDB: "True"
