apiVersion: apps/v1
kind: Deployment
metadata:
  name: xstream-backend
  labels:
    app: xstream-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: xstream-backend
  template:
    metadata:
      labels:
        app: xstream-backend
    spec:
      containers:
      - name: xstream-backend
        image: xstream-backend:local
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
        readinessProbe:
          tcpSocket:
            port: 8000
          initialDelaySeconds: 20
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 8000
          initialDelaySeconds: 60
          periodSeconds: 20
        envFrom:
        - secretRef:
            name: xstream-backend-env
            optional: false
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
