apiVersion: v1
kind: Service
metadata:
  name: xstream-backend-svc
  labels:
    app: xstream-backend
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8000"
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8000
    nodePort: 30080
    protocol: TCP
  selector:
    app: xstream-backend
